spring.application.name: spring-data-service

server.port: 8081

management.server.port: 8082

spring.data.rest.basePath: /api
---
spring.profiles: docker
spring:
  data:
    cassandra:
      port: 9042
      contact-points: host.docker.internal
      keyspace-name: betterbotz
      local-datacenter: dc1
      schema-action: create-if-not-exists
---
spring.profiles: kubernetes
spring.cloud.kubernetes.enabled: true
spring.cloud.kubernetes.config.enabled: true
spring.cloud.kubernetes.config.sources.namespace: spring-data-service
spring.cloud.kubernetes.reload.enabled: true
spring.cloud.kubernetes.reload.mode: event
spring.cloud.kubernetes.reload.strategy: refresh
kubernetes.trust.certificates: true
management.endpoint.restart.enabled: true
     